const express=require("express");
const router=express.Router();
const {Signup,Login,userVerification}=require("../util/middleware");
const controller=require("../controllers/controller");
router.get("/allHoldings",controller.getAllHoldings);
router.get("/allOrders",controller.getAllOrders);
router.post("/newOrders",controller.newOrders);
router.post("/signup",Signup);
router.post("/login",Login);
router.post("/",userVerification);
router.post("/depositfunds",controller.depositFunds);
router.get("/getfunds",controller.getfunds);
router.post("/withdrawfunds", controller.withdrawFunds);
router.post("/userVerification",controller.userVerification);
module.exports=router;